version: '3'
services:
  chrometest:
    build:
      context: .
      dockerfile: dockerfile
    container_name: chromeplaywright
    command: ["npx", "playwright", "test", "--project=chromium", "/tests"]
    networks:
      - testnet
  firefoxtest:
    build:
      context: .
      dockerfile: dockerfile
    container_name: firefoxplaywright
    command: ["npx", "playwright", "test", "--project=firefox", "/tests"]
    networks:
      - testnet
networks:
  testnet: